import makeFonePayPayment from '@/payment-gateways/fonepay'
import payFromKhalti, { validateKhaltiPayment } from '@/payment-gateways/khalti';
import Head from 'next/head'
import { useEffect } from 'react'

export default function Home() {
  useEffect(() => {
    payFromKhalti()
    // makeFonePayPayment()
  }, [])
  return (
    <>
      <Head>
        <title>Payment Gateway Integration Tests</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      </main>
    </>
  )
}
